project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - states/california/california.qmd
    - states/*/index.qmd
    - regions/*/index.qmd

website:
  title: "Rainfall reports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: States
        menu:
          - states/california/california.qmd
          - states/colorado/index.qmd
          - states/florida/index.qmd
          - states/louisiana/index.qmd
          - states/massachusetts/index.qmd
          - states/minnesota/index.qmd
          - states/new-jersey/index.qmd
          - states/new-york/index.qmd
          - states/pennsylvania/index.qmd
          - states/tennessee/index.qmd
      - text: Regions
        menu:
          - regions/norcal-pnw-rockies/index.qmd
          - regions/socal-southwest-gulf/index.qmd
          - regions/northeast/index.qmd
          - regions/south-midwest/index.qmd

format:
  html:
    theme: cosmo
    css: styles/report.css
    toc: true
    toc-location: left
    mainfont: "DM Sans"
    fontsize: 1.05em

engine: knitr

execute:
  echo: false
  warning: false
  message: false
  fig-format: png
knitr:
  opts_chunk:
    dev: png
