# Write california-narration.txt for ElevenLabs (prose only; numbers spelled out).
# Keep in sync with narrative sections 01–06 in states/california/california.qmd.
write_ca_narration <- function(path, ...) {
  args <- list(...)
  n <- function(x) {
    x <- as.integer(x)
    if (requireNamespace("english", quietly = TRUE)) {
      return(english::as.words(x))
    }
    as.character(x)
  }
  pct <- function(x) sprintf("%.0f", as.numeric(x))
  err <- function(x) gsub("\\.", " point ", sprintf("%.3f", as.numeric(x)), fixed = TRUE)

  txt <- paste0(
    "CMS TEAM in California: Reading the State's Roster, Risk and Readiness.\n\n",
    "In brief. California carries ", n(args$SCOPE_N), " of the ", n(args$NATIONAL_TOTAL),
    " hospitals in the Transforming Episode Accountability Model, the largest state roster in the country, about ",
    pct(args$national_share), " percent of the national list. Exposure is concentrated in a handful of metro markets, not spread evenly across the state. On readmissions, California's position depends entirely on which condition you look at: surgical cohorts that map to TEAM look stronger than the national average, and every medical condition tracked runs the other way. That split starts counting for more in Performance Year two, when a hospital-wide readmission measure enters the quality score.\n\n",
    "Section one. At a glance.\n\n",
    "California carries the largest state roster in the country's newest mandatory hospital payment program. ",
    "When the Centers for Medicare and Medicaid Services built the list of hospitals required to join ",
    "the Transforming Episode Accountability Model, known as TEAM, it put ", n(args$SCOPE_N),
    " of them in California, spread across ", n(args$SCOPE_CBSA_N),
    " metropolitan markets, out of ", n(args$NATIONAL_TOTAL), " hospitals nationwide. ",
    "That's close to ", pct(args$national_share), " percent of the entire national roster sitting inside one state. ",
    "Of California's ", n(args$SCOPE_N), ", ", n(args$mandatory_n), " were mandated in. Only ",
    n(args$voluntary_n), " joined voluntarily. All of them are locked in for the model's full run, ",
    args$performance_window, ".\n\n",
    "It's worth pausing on what TEAM actually asks of a hospital, because it's a real departure from ",
    "how Medicare used to pay for surgery. The old model paid piece by piece: a fee for the operation, ",
    "a separate fee for the hospital stay, and then whatever came after, a stay in a skilled nursing facility, ",
    "home health visits, or a return trip to the emergency room, billed and reimbursed on its own. ",
    "TEAM collapses all of that into one thirty-day window. A hospital is now accountable, financially, ",
    "for everything that happens to a patient for thirty days after five kinds of procedures: hip and knee ",
    "replacement, spinal fusion, coronary bypass, surgical repair of a hip fracture, and major bowel surgery. ",
    "Spend too much across that window, or let the patient come back in, and it's the hospital's number that moves, ",
    "not some other part of the system's.\n\n",
    "Section two. Where the mandate sits.\n\n",
    "Start with geography, because California's exposure is not spread evenly across the state, it's concentrated ",
    "in a handful of places. The San Francisco, Oakland, Fremont market alone accounts for ", n(args$sf_n),
    " hospitals, about ", pct(args$sf_pct), " percent of the state's total, and that makes it the ",
    args$sf_rank, " largest TEAM market in the entire country, behind only New York. Riverside, San Bernardino, ",
    "and Ontario, the Inland Empire, comes in at ", n(args$riverside_n), " hospitals, ",
    pct(args$riverside_pct), " percent of the state, and ranks ", args$riverside_rank, " nationally. ",
    "San Diego, Chula Vista, and Carlsbad adds another ", n(args$sd_n), ", about ",
    pct(args$sd_pct), " percent. The remaining markets are smaller; the charts in the written report show every CBSA and how Rainfall groups them into regions.\n\n",
    "There's also a system-ownership story worth knowing before you get to the performance data. About ",
    pct(round(100 * args$multi_system_hospital_n / args$SCOPE_N, 0)),
    " percent of California's roster, ", n(args$multi_system_hospital_n), " of the ",
    n(args$SCOPE_N), " hospitals, sits in ", n(args$multi_system_system_n),
    " multi-hospital systems with at least two TEAM sites in the state, and the single largest, ",
    args$largest_system_label, ", accounts for ", n(args$largest_system_n),
    " hospitals on its own, about ", pct(args$largest_system_pct),
    " percent of the entire state roster. When one system holds a double-digit share of a state's participants, ",
    "decisions about episode standards, post-acute contracting, and data infrastructure tend to get made centrally, ",
    "which changes who actually needs to be in the room when a hospital plans its TEAM readiness.\n\n",
    "Grouping those markets into regions sharpens the picture further. The Bay Area holds ", n(args$bay_n),
    " hospitals, about ", pct(args$bay_pct),
    " percent of the state. The Inland Empire holds ", n(args$inland_n), ", ",
    pct(args$inland_pct), " percent. Greater Los Angeles, despite being the state's largest metro area by population, ",
    "contributes a single hospital to the entire list, the clearest illustration that CMS built TEAM around ",
    "specific metropolitan statistical areas, not around where the most hospitals happen to be.\n\n",
    "Section three. Readmission performance where TEAM pays.\n\n",
    "Now to the part of the analysis that actually predicts how these hospitals are likely to fare under the model: ",
    "readmissions. Medicare publishes an excess readmission ratio for nearly every hospital in the country, ",
    "condition by condition. It compares how many patients actually came back within thirty days against how many you'd expect, ",
    "given that hospital's specific mix of patients. A ratio under one means fewer readmissions than expected. Over one means more. ",
    "Because TEAM pays hospitals based on the thirty-day arc after surgery, a hospital's existing readmission pattern is about ",
    "the closest thing available to a preview of how it will perform under the new rules.\n\n",
    "This analysis matched all ", n(args$SCOPE_N),
    " California hospitals to Medicare's public readmissions file using their federal certification numbers, ",
    "so the linkage is exact, hospital by hospital. ",
    n(args$reporting_n), " of the ", n(args$SCOPE_N),
    " have at least one reportable ratio in the current file; the other ", n(args$non_reporting_n),
    " fall below Medicare's minimum case-volume threshold across every condition tracked. The data covers ", args$hrrp_period, ".\n\n",
    "Here's where the story gets genuinely interesting, because California's position depends entirely on which condition you're looking at. ",
    "On the two surgical categories that map most directly onto what TEAM actually pays for, hip and knee replacement and coronary bypass, ",
    "California outperforms the nation. The average ratio for joint replacement across California's TEAM hospitals is ",
    err(args$hk_scope), ", against ", err(args$hk_nat), " nationally. Bypass surgery comes in at ",
    err(args$cabg_scope), " against ", err(args$cabg_nat), " nationally. Both numbers sit on the favorable side of the line.\n\n",
    "But shift to the medical conditions, the ones that aren't part of TEAM's five surgical categories but draw on the same hospital floors, ",
    "the same discharge planners, and the same post-acute partners, and the pattern flips. Heart attack patients in California come back at a ratio of ",
    err(args$ami_scope), " against ", err(args$ami_nat), " nationally. Heart failure runs ",
    err(args$hf_scope), " against ", err(args$hf_nat), ". Pneumonia is the widest gap of all: ",
    err(args$pn_scope), " in California against ", err(args$pn_nat), " nationally. COPD is close to even, ",
    err(args$copd_scope), " against ", err(args$copd_nat), ". On every one of these medical conditions, ",
    "California hospitals are readmitting more patients than their case mix would predict, while the rest of the country is essentially running right at expectation.\n\n",
    "Takeaway. California looks stronger on the surgical readmissions that map most directly to TEAM episodes, but hotter on medical readmissions statewide, ",
    "so a hospital cannot assume its joint-replacement or bypass performance covers the rest of the house.\n\n",
    "It's also worth knowing that these averages hide as much as they reveal. California's strong joint-replacement number isn't a story of uniform excellence, ",
    "it's a story of standout performers pulling the average down. ",
    pct(args$hk_scope_above), " percent of California's reporting hospitals are still sitting above the expected line on joint replacement, ",
    "almost identical to ", pct(args$hk_nat_above), " percent nationally, even though the state average looks meaningfully better. ",
    "Bypass surgery is the one place where the spread genuinely favors California: only ",
    pct(args$cabg_scope_above), " percent of hospitals sit above the line, against ",
    pct(args$cabg_nat_above), " percent nationally. On the medical side, the spread confirms the averages: ",
    pct(args$ami_scope_above), " percent of California hospitals exceed expectation on heart attack and ",
    pct(args$pn_scope_above), " percent on pneumonia, against ",
    pct(args$ami_nat_above), " and ", pct(args$pn_nat_above), " percent nationally. Heart failure sits at ",
    pct(args$hf_scope_above), " against ", pct(args$hf_nat_above), ", and COPD at ",
    pct(args$copd_scope_above), " against ", pct(args$copd_nat_above), ".\n\n",
    "For your hospital, the number that matters is the excess readmission ratio tied to your CMS certification number in Medicare's public file, not California's average. ",
    "The statewide figures tell you almost nothing about where you stand; your CCN-level ratios are already public.\n\n",
    "Section four. What changes in Performance Year two.\n\n",
    "That split between surgical and medical performance matters more starting next year than it did this year, because the scoring itself is about to change. ",
    "TEAM's first performance year leaned in part on a patient-safety composite measure that CMS is retiring after year one. ",
    "From Performance Year two onward, the quality score instead draws on a broader hospital-wide, all-cause readmission measure, ",
    "plus two new patient-harm measures covering falls with injury and postoperative respiratory failure, ",
    "plus a measure tracking risk-standardized death among surgical patients who develop complications. ",
    "The existing patient-reported outcome measure for hip and knee replacement continues, and a new measure tracking information transfer between care settings joins in year three, ",
    "specific to joint replacement and spinal fusion episodes. The hospital-wide readmission measure is the one to watch, ",
    "because unlike the outgoing safety composite, it does not distinguish between a surgical patient and a medical one. It counts everyone. ",
    "That's precisely the measure where California's medical-condition weakness is going to show up, at the exact moment it starts counting more toward the score.\n\n",
    "In plain terms, starting in Performance Year two, CMS blends all of a hospital's readmissions into one hospital-wide score, not just the surgical patients TEAM pays for directly. ",
    "California's TEAM hospitals look relatively strong on hip and knee and bypass readmissions, but above national expectation on the medical conditions in this file. ",
    "A hospital that is fine on surgery can still see that broader measure pull its composite quality score down when it starts counting in reconciliation.\n\n",
    "A few other pieces are already locked in. Spinal fusion has been one of TEAM's five procedure categories from the start, but the definition is expanding: ",
    "three new diagnosis-related-group codes for extensive and complex spinal fusion procedures take effect for discharges on or after October first, twenty twenty-six, ",
    "and they fold directly into TEAM's existing spinal fusion category. Separately, the way Medicare calculates target prices is being recalibrated. ",
    "Starting in Performance Year two, the normalization factor that adjusts those prices will be calculated across a full three-year baseline instead of just the most recent year.\n\n",
    "There's also a change worth knowing about even for hospitals convinced TEAM is their only concern. Washington finalized a second, entirely separate mandatory bundled-payment program for joint replacement specifically, ",
    "covering nearly every acute-care hospital in the country that isn't already in TEAM. It takes effect January first, twenty twenty-eight, and it explicitly excludes hospitals already participating in TEAM. ",
    "The practical effect is that California's ", n(args$SCOPE_N), " TEAM hospitals will keep operating on a thirty-day episode window all the way through twenty thirty, ",
    "while most of their peers elsewhere in the state and the country shift onto a ninety-day window that also reaches into outpatient procedures and adds ankle replacement to the covered list.\n\n",
    "Section five. Considerations for hospital leadership.\n\n",
    "So what should an executive actually do with all of this? Start by confirming your own hospital's status using its federal certification number rather than its name, ",
    "because names drift between internal systems and Medicare's files in ways that can create real confusion about who's actually on the list and on what terms. ",
    "Pull your own condition-level readmission ratios directly, because the statewide pattern tells you almost nothing about where any one hospital stands. ",
    "Start extending the discipline that's clearly working in surgical discharge planning over to medical admissions, because that's exactly where the scoring is about to lean harder. ",
    "Revisit post-acute routing decisions using the actual evidence rather than habits inherited from older programs. ",
    "And calibrate expectations to what the evidence actually shows: real, durable savings are possible, but they come from sustained change in post-acute patterns over time, not from a single strong quarter.\n\n",
    "Section six. Methods and limitations.\n\n",
    "One thing this analysis deliberately does not do is put a dollar figure on any of this. Medicare doesn't publish what an individual hospital's target price is, ",
    "or what its baseline episode spending looks like, and without that, any specific dollar exposure number circulating for California is somebody's estimate dressed up as a fact. ",
    "What the evidence does support, from Medicare's own evaluations of earlier bundled-payment efforts, is a rough sense of where the money actually moves: ",
    "in the first mandatory joint-replacement year, hospitals cut discharges to institutional post-acute care by about two point nine percentage points, ",
    "while a longer voluntary bundled program showed roughly eleven hundred sixty-six dollars less per episode over time, mostly from post-acute use rather than the inpatient stay. ",
    "Savings show up gradually, through sustained changes in where patients go after discharge, not in the first reconciliation cycle. ",
    "Use the written report for citations, glossary, and downloadable tables.\n"
  )
  writeLines(txt, path, useBytes = FALSE)
}
